### PR TITLE
Added Irish/ga

### PR DESCRIPTION
**Pull request by JoeyTatu**
Added Irish.

### CODE REVIEW

**Comment by JoeyTatu** [comment]
image
image
Hello?!

**Comment by JoeyTatu** [comment]
Clearly this is no longer maintained. If you want Irish, do it yourself.

**Comment by abh** [comment]
Hi @JoeyTatu! Thanks for doing the translation. I was working on something else and didn't get to adding this and pushing it out this weekend.

**Comment by abh** [comment]
Re-opening to merge.

**Pull request closed without merging**
