### PR TITLE
Update join.html

### PR DESCRIPTION
**Pull request by lgt945**
update some inappropriate translations.

### CODE REVIEW

**Comment by felixonmars** [comment]
+1 on the Chinese translation improvements.

**Comment by abh** [comment]
thanks @lgt945 and thank you @felixonmars for the +1 (since I can't read any of it!).

**Comment by lgt945** [comment]
> +1 on the Chinese translation improvements.

thanks dalao~

**Comment by lgt945** [comment]
> thanks @lgt945 and thank you @felixonmars for the +1 (since I can't read any of it!).

thanks for merging , first merge :)

**Pull request merged**
