### PR TITLE
Various fixes and updates to website

### PR DESCRIPTION
**Pull request by PoolMUC**
Fixed typos, improved wordings, updated translations, updated URLs and links, upgraded URL schemata, ...

### CODE REVIEW

**Comment by abh** [comment]
Very nice! Will you leave a comment when you are stopping for the day? Looks like you keep finding more!

**Comment by PoolMUC** [comment]
> Will you leave a comment when you are stopping for the day? Looks like you keep finding more!

Yeah, I think I will stop now...

Sorry, I'll use a different approach next time, e.g., explore use of the "work in progress/draft" feature.

**Comment by PoolMUC** [comment]
In the language-specific `join.html` files, there is the code fragment `[% i = 0; FOR server = combust.servers_with_urls; %]`. It seems that is broken somehow. At least in my browsers, it only shows the introductory "Here are a few servers with traffic/load graphs:" (or respective translated) text.

I don't know how to fix this. If unfixable (e.g., because the backend system has changed and no longer provides the needed data/functionality), it could probably be removed.

**Comment by abh** [comment]
> Yeah, I think I will stop now...
>
> Sorry, I'll use a different approach next time, e.g., explore use of the "work in progress/draft" feature.

No apologies necessary, I really appreciate this!

**Comment by abh** [comment]
Ah yeah, the "server_with_urls" thing was a feature where operators could provide links to their server graphs / metrics, but I was worried about spam / junk, so I never made it so users could input the links on their own and whatever links were there were on servers no longer in the pool.

I think we could just remove that feature; it's not clear it's worth bringing back.

**Comment by PoolMUC** [comment]
> I think we could just remove that feature

Ok. I am working on another PR addressing some further minor nits, will address it there, and push once you have committed the current PR (just so I can better keep track of what is already addressed, and what is still open - and smaller PRs make for better reviewing...).

**Pull request merged**
