### PR TITLE
Norwegian (Nynorsk) Translation

### PR DESCRIPTION
**Pull request by nilsjha**
Created nn (ISO 639-1 language code) Norwegian (Nynorsk) translation of the main branch by adding nn.po in the i18n/ -sub-directory  as well as translating the associated files located under the docs/ntppool/ -sub-directory.

Norwegian (Nynorsk) (my native written language) is understandable and very similar to Norwegian (Bokmål). Until the Bokmål (nb) translation is completed, Nynorsk might also be helpful for those who are better understanding Norwegian in general than English.

For more information about similarities, please have a look on Wikipedia
https://en.wikipedia.org/wiki/Norwegian_language

For translating Norwegian - English in general The University of Oslo provides great dictionaries online: http://www.nob-ordbok.uio.no/

(Please also have in mind I'm currently newbie using Git, not all of the commits are too well described - but I'm mastering it better as i get more experience in the field of software development /translations)

Any questions, improvements, please comment.

Thanks,
Nils

### CODE REVIEW

**Comment by nilsjha** [comment]
Just wondering if anybody can have a look on this translation, then maybe pull it ? (one year after original pull request....)

**Comment by abh** [comment]
Whoops, thank you! I'll get it up on the beta site. 

actually, before I merge -- isn't a Bokmål translation very unlikely? If so, would it make more sense to call it "no", so the URL will be ntppool.org/no/ ?

**Comment by nilsjha** [comment]
Thanks for the reply! I agree on having one translation might be the cleanest and most efficient way. I've not seen any interest for translating the entire site into Bokmål the last year. Calling it"no" makes perfectly sense for me, as that is also universal for all Norwegian language, both Nynorsk and Bokmål. 

I unfortunately messed up right now, by deleting the fork just before you replied. (Doh!) Sorry if that creates any trouble. I've a local repo on my PC, so we the opportunity to restore/ re-fork if need.

**Comment by abh** [comment]
It's on the beta site now -- let me know if it's ready to mark as "not testing". https://web.beta.grundclock.com/no/

**Comment by abh** [comment]
@nilsjha  There's a bit of formatting/markup tweaks to be done at https://web.beta.grundclock.com/no/join.html

**Pull request merged**
